// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DATABASE_URL uses Supavisor pooled connection (port 6543) for runtime queries
    url: process.env["DATABASE_URL"],
    // DIRECT_URL uses direct connection (port 5432) for migrations
    directUrl: process.env["DIRECT_URL"],
  },
});
